# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: '3.3'

services:
  notification:
    environment:
      - LANGUAGES=fr,en
      - SENTRY_DSN=${SENTRY_DSN}
  
  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION:-latest}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - APPLICATION_CONFIG_URL=http://config:2021
      - OPENHIM_URL=http://openhim-core:5001/fhir
      - CONFIRM_REGISTRATION_URL=http://openhim-core:5001/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - HOSTNAME=${HOSTNAME}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - INFOBIP_GATEWAY_ENDPOINT=${INFOBIP_GATEWAY_ENDPOINT}
      - INFOBIP_API_KEY=${INFOBIP_API_KEY}
      - INFOBIP_SENDER_ID=${INFOBIP_SENDER_ID}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - SENTRY_DSN=${SENTRY_DSN}

    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT = 100

  gateway:
    environment:
      - LANGUAGES=fr,en
      - SENTRY_DSN=${SENTRY_DSN}
      - COUNTRY=HTI

  workflow:
    environment:
      - LANGUAGES=fr,en
      - SENTRY_DSN=${SENTRY_DSN}

  auth:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

  user-mgnt:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

  config:
    environment:
      - NODE_ENV=production
      - SENTRY_DSN=${SENTRY_DSN}

  metrics:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

  search:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

  webhooks:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

